# fly.toml app configuration file generated for django-apm-tests on 2023-08-10T08:38:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-apm-tests"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "./pos-release.sh"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
