# Generated by Django 4.2.4 on 2023-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(db_index=True, to="core.author"),
        ),
    ]
